name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pillow pyinstaller
      - name: Build EXE
        run: pyinstaller --onefile --windowed flatness_gui.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatness_gui.exe.zip
          path: dist/flatness_gui.exe
