
---

## 5️⃣ `.github/workflows/build.yml`

```yaml
name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pillow pyinstaller

      - name: Build EXE with spec file
        run: |
          pyinstaller flatness_calculator.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatness_gui.exe
          path: dist/flatness.exe
