name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --icon=assets/app_icon.ico --add-data "assets/logo.png;assets" main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: flatness_calculator
          path: dist/flatness_calculator.exe
